version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/corona-frontend-dev
permissions:
  - object: /home/ubuntu/corona-frontend-dev
    owner: ubuntu
  - object: /home/ubuntu/corona-frontend-dev/*/**
    owner: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
  AfterInstall:
    - location: scripts/after-install.sh
  ApplicationStart:
    - location: scripts/application-start.sh