name: corona-frontend build CI

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies and Surge
        run: |
          npm install
          npm install surge --global

      - name: Build React Application
        run: npm run build